version: 1
suite: client_configurations_remaining
finding: PenTest-001
defaults:
  auth: low_priv
  required: true
  headers:
    Content-Type: application/json
cases:
- id: GET-configurations-obligors-bufferDays-findByTrade
  method: GET
  path: /api/configurations/obligors/bufferDays/findByTrade/{{trade_id}}
  mutate: false
  required: false
- id: GET-configurations-retainage-reserve-client
  method: GET
  path: /api/configurations/{{foreign_provider_id}}/retainage-reserve
  mutate: false
  required: false
- id: GET-configurations-bankAccounts-search
  method: GET
  path: /api/configurations/bankAccounts/search
  mutate: false
  required: false
- id: GET-configurations-bankAccounts-findByClientAndRole
  method: GET
  path: /api/configurations/bankAccounts/findByClientAndRole
  mutate: false
  required: false
- id: GET-configurations-bankAccounts-download-excel
  method: GET
  path: /api/configurations/bankAccounts/download/excel
  mutate: false
  required: false
- id: GET-configurations-bankAccounts-download-excel-findByClientAndRole
  method: GET
  path: /api/configurations/bankAccounts/download/excel/findByClientAndRole
  mutate: false
  required: false
- id: GET-configurations-bankAccounts-download-csv
  method: GET
  path: /api/configurations/bankAccounts/download/csv
  mutate: false
  required: false
- id: GET-configurations-labels-findById
  method: GET
  path: /api/configurations/labels/findById
  mutate: false
  required: false
- id: GET-configurations-labels-findByClient
  method: GET
  path: /api/configurations/labels/findByClient
  mutate: false
  required: false
- id: GET-configurations-labels-providerByHolding
  method: GET
  path: /api/configurations/labels/providerByHolding
  mutate: false
  required: false
- id: GET-configurations-rates-by-client
  method: GET
  path: /api/configurations/rates/by-client
  mutate: false
  required: false
- id: GET-configurations-rates-sofrHolidays
  method: GET
  path: /api/configurations/rates/sofrHolidays
  mutate: false
  required: false
- id: GET-configurations-rates-applied-today
  method: GET
  path: /api/configurations/rates/applied/today
  mutate: false
  required: false
- id: GET-configurations-rates-purchaseDate-change
  method: GET
  path: /api/configurations/rates/purchaseDate/change
  mutate: false
  required: false
- id: GET-configurations-capacity-getClientCapacity
  method: GET
  path: /api/configurations/capacity/getClientCapacity
  mutate: false
  required: false
- id: GET-configurations-capacity-getClientTotalCapacity
  method: GET
  path: /api/configurations/capacity/getClientTotalCapacity
  mutate: false
  required: false
- id: GET-configurations-capacity-getObligorCapacity
  method: GET
  path: /api/configurations/capacity/getObligorCapacity
  mutate: false
  required: false
- id: GET-configurations-capacity-providers-download-excel
  method: GET
  path: /api/configurations/capacity/providers/download/excel
  mutate: false
  required: false
- id: GET-configurations-capacity-providers-download-csv
  method: GET
  path: /api/configurations/capacity/providers/download/csv
  mutate: false
  required: false
- id: GET-configurations-capacity-obligors-download-excel
  method: GET
  path: /api/configurations/capacity/obligors/download/excel
  mutate: false
  required: false
- id: GET-configurations-capacity-obligors-download-csv
  method: GET
  path: /api/configurations/capacity/obligors/download/csv
  mutate: false
  required: false
- id: GET-configurations-obligors
  method: GET
  path: /api/configurations/obligors
  mutate: false
  required: false
- id: GET-configurations-obligors-download-excel
  method: GET
  path: /api/configurations/obligors/download/excel
  mutate: false
  required: false
- id: GET-configurations-obligors-download-csv
  method: GET
  path: /api/configurations/obligors/download/csv
  mutate: false
  required: false
- id: GET-configurations-obligors-trades-buffer-days-download-excel
  method: GET
  path: /api/configurations/obligors/trades/buffer-days/download/excel
  mutate: false
  required: false
- id: GET-configurations-obligors-reserves-download-excel
  method: GET
  path: /api/configurations/obligors/reserves/download/excel
  mutate: false
  required: false
- id: GET-configurations-obligors-admin-buffer-days-download-excel
  method: GET
  path: /api/configurations/obligors/admin-buffer-days/download/excel
  mutate: false
  required: false
- id: GET-configurations-obligors-formUpdate
  method: GET
  path: /api/configurations/obligors/formUpdate
  mutate: false
  required: false
- id: GET-configurations-getClientValidations
  method: GET
  path: /api/configurations/getClientValidations
  mutate: false
  required: false
- id: GET-configurations-validations-investors
  method: GET
  path: /api/configurations/validations/investors
  mutate: false
  required: false
- id: GET-configurations-providers-download-excel
  method: GET
  path: /api/configurations/providers/download/excel
  mutate: false
  required: false
- id: GET-configurations-providers-download-csv
  method: GET
  path: /api/configurations/providers/download/csv
  mutate: false
  required: false
- id: GET-configurations-tradeFees-search
  method: GET
  path: /api/configurations/tradeFees/search
  mutate: false
  required: false
- id: GET-configurations-tradeDocuments-findByAll
  method: GET
  path: /api/configurations/tradeDocuments/findByAll
  mutate: false
  required: false
- id: GET-configurations-tradeDocuments-findByClient
  method: GET
  path: /api/configurations/tradeDocuments/findByClient
  mutate: false
  required: false
- id: GET-configurations-exists-company-documents
  method: GET
  path: /api/configurations/exists-company-documents
  mutate: false
  required: false
- id: GET-configurations-documents-companies-search
  method: GET
  path: /api/configurations/documents/companies/search
  mutate: false
  required: false
- id: GET-configurations-tradeFees-download-excel
  method: GET
  path: /api/configurations/tradeFees/download/excel
  mutate: false
  required: false
- id: GET-configurations-tradeFees-download-csv
  method: GET
  path: /api/configurations/tradeFees/download/csv
  mutate: false
  required: false
- id: GET-configurations-supporting-documents-download-excel
  method: GET
  path: /api/configurations/supporting-documents/download/excel
  mutate: false
  required: false
- id: GET-configurations-supporting-documents-download-csv
  method: GET
  path: /api/configurations/supporting-documents/download/csv
  mutate: false
  required: false
- id: GET-configurations-tradeFees-findByClientAndInvestor
  method: GET
  path: /api/configurations/tradeFees/findByClientAndInvestor
  mutate: false
  required: false
- id: GET-configurations-validations-tenor-days
  method: GET
  path: /api/configurations/validations/tenor-days
  mutate: false
  required: false
- id: GET-configurations-validations-tenor-days-fields
  method: GET
  path: /api/configurations/validations/tenor-days/fields
  mutate: false
  required: false
- id: GET-configurations-validations-tenor-days-formula
  method: GET
  path: /api/configurations/validations/tenor-days/formula
  mutate: false
  required: false
- id: GET-configurations-validations-tenor-days-investors
  method: GET
  path: /api/configurations/validations/tenor-days/investors
  mutate: false
  required: false
- id: GET-configurations-validations-tenor-days-obligors
  method: GET
  path: /api/configurations/validations/tenor-days/obligors
  mutate: false
  required: false
