"""Extract Spring controller mappings from TAP API source tree.

Outputs a curated YAML inventory of (method, path, controller_class) suitable
for `cases/99_discovery_catalog.yaml`.

Usage:
    python tools/extract_paths_from_java.py \
        --src /Users/guedaf/CapMotion/repositories/tap/tap-api/src/main/java \
        --out tools/discovery_catalog.yaml
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

import yaml

_HTTP_METHOD_TO_ANNOTATION = {
    "GET": "GetMapping",
    "POST": "PostMapping",
    "PUT": "PutMapping",
    "DELETE": "DeleteMapping",
    "PATCH": "PatchMapping",
    "HEAD": "RequestMapping(method=RequestMethod.HEAD)",
    "OPTIONS": "RequestMapping(method=RequestMethod.OPTIONS)",
}


@dataclass
class Endpoint:
    method: str
    path: str
    class_name: str


@dataclass
class ClassInfo:
    base_path: str = ""
    endpoints: list[Endpoint] = field(default_factory=list)


_CLASS_MAPPING = re.compile(
    r"@RequestMapping\(\s*(?:[^()]*?\b(?:value|path)\s*=\s*)?\"([^\"]+)\""
)
_METHOD_MAPPING = re.compile(
    r"@(Get|Post|Put|Delete|Patch)Mapping\(\s*(?:[^()]*?\b(?:value|path)\s*=\s*)?\"([^\"]+)\""
)
_METHOD_MAPPING_EMPTY = re.compile(r"@(Get|Post|Put|Delete|Patch)Mapping(?!\s*\()")
_MAPPING_VALUE = re.compile(r"value\s*=\s*\"([^\"]+)\"")
_PUBLIC_CLASS = re.compile(r"public\s+(?:final\s+|abstract\s+)?class\s+(\w+)")


def extract(src_root: Path) -> dict[str, ClassInfo]:
    classes: dict[str, ClassInfo] = defaultdict(ClassInfo)
    for java_file in src_root.rglob("*.java"):
        text = java_file.read_text(encoding="utf-8", errors="ignore")
        class_match = _PUBLIC_CLASS.search(text)
        if not class_match:
            continue
        class_name = class_match.group(1)
        info = classes[class_name]
        for match in _CLASS_MAPPING.finditer(text):
            info.base_path = _normalize(match.group(1))

        for method_match in _METHOD_MAPPING.finditer(text):
            http = method_match.group(1).upper()
            value = method_match.group(2)
            full_path = _normalize(f"{info.base_path}{value}")
            info.endpoints.append(Endpoint(method=http, path=full_path, class_name=class_name))

        for empty_match in _METHOD_MAPPING_EMPTY.finditer(text):
            http = empty_match.group(1).upper()
            full_path = _normalize(info.base_path)
            info.endpoints.append(Endpoint(method=http, path=full_path, class_name=class_name))

    return {k: v for k, v in classes.items() if v.endpoints}


def _normalize(path: str) -> str:
    if not path.startswith("/"):
        path = "/" + path
    if not path.startswith("/api"):
        return path
    return path.rstrip("/") or path


def render_yaml(classes: dict[str, ClassInfo]) -> str:
    seen: set[tuple[str, str]] = set()
    rows: list[dict[str, str]] = []
    for info in sorted(classes.values(), key=lambda c: (c.base_path, c.endpoints[0].class_name if c.endpoints else "")):
        for endpoint in sorted(info.endpoints, key=lambda e: (e.path, e.method)):
            key = (endpoint.method, endpoint.path)
            if key in seen:
                continue
            seen.add(key)
            rows.append(
                {
                    "controller": endpoint.class_name,
                    "method": endpoint.method,
                    "path": endpoint.path,
                }
            )
    header = {
        "version": 1,
        "suite": "discovery_catalog",
        "finding": "PenTest-001",
        "note": "Auto-generated by tools/extract_paths_from_java.py; review before use.",
        "cases": rows,
    }
    return yaml.safe_dump(
        header,
        sort_keys=False,
        allow_unicode=True,
        width=4096,
        default_flow_style=False,
        explicit_start=False,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Extract Spring mappings from TAP API source.")
    parser.add_argument("--src", required=True, type=Path, help="Path to src/main/java root")
    parser.add_argument("--out", required=True, type=Path, help="Output YAML file")
    parser.add_argument("--filter", action="append", default=[], help="Substring filters for controller name")
    args = parser.parse_args()

    classes = extract(args.src)
    if args.filter:
        classes = {k: v for k, v in classes.items() if any(f in k for f in args.filter)}

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_yaml(classes), encoding="utf-8")
    total = sum(len(c.endpoints) for c in classes.values())
    print(f"Extracted {total} endpoints from {len(classes)} controllers -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
